# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.2

# Mod Properties
mod_version=5.3.1
maven_group=dev.kir
archives_base_name=sync

# Dependencies
fabric_version=0.92.3+1.20.1
tr_energy_version=3.0.0
satin_version=1.14.0
cloth_version=11.1.136
modmenu_version=7.2.2
trinkets_version=3.7.2
requiem_version=2.0.0-beta.8
origins_version=1.10.0
apoli_version=2.9.0
haema_version=1.9.9+1.18.2
smartrecipes_version=0.2.1+1.20
crowdin_translate_version=1.4+1.19-pre2